### PR TITLE
Added Docker for sample site

### PR DESCRIPTION
**Pull request by valdisiljuconoks**

### CODE REVIEW

**Comment by valdisiljuconoks** [comment]
@patkleef could you test this out by running Docker locally? for some reason I start to receive `Service 'geta-googleproductfeed-sample-web' failed to build: hcsshim::CreateComputeSystem ....: The virtual machine could not be started because a required feature is not installed.` can't figure out where / what is missing...

**Comment by valdisiljuconoks** [comment]
#11

**Comment by valdisiljuconoks** [comment]
@patkleef so what do we do with this? merge?

**Comment by brianweet** [comment]
Looks like there's something wrong with the dbs?
image

**Comment by valdisiljuconoks** [comment]
@patkleef @brianweet any help with Docker would be appreciated as I can't get it working locally..

**Comment by brianweet** [comment]
@valdisiljuconoks Yeah sure, what's the problem?
If it's regarding my previous comment: I think the db files are corrupt, I will update them to see if that helps.

**Comment by patkleef** [comment]
Works for me now. Thanks @brianweet

**Pull request merged**
